export const INVALID_INPUT = 'INVALID_INPUT';
export const INCORRECT_CREDENTIALS = 'INCORRECT_CREDENTIALS';
export const EMAIL_TAKEN = 'EMAIL_TAKEN';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const DUPLICATE_FIELDS = 'DUPLICATE_FIELDS';
export const REQUEST_ERROR = 'REQUEST_ERROR';