export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CHECK_SESSION = 'CHECK_SESSION';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const SET_AUTH_ERR_MSG = 'SET_AUTH_ERR_MSG';
export const CLEAR_AUTH_ERR_MSG = 'CLEAR_AUTH_ERR_MSG';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

export const GET_FEED_START = 'GET_FEED_START';
export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS';