export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CHECK_SESSION = 'CHECK_SESSION';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const SET_AUTH_ERR_MSG = 'SET_AUTH_ERR_MSG';
export const CLEAR_AUTH_ERR_MSG = 'CLEAR_AUTH_ERR_MSG';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_CREATE_POST_LOADING = 'SET_CREATE_POST_LOADING';
export const SET_GET_USER_LOADING = 'SET_CREATGET_USER_LOADING';

export const GET_FEED_START = 'GET_FEED_START';
export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS';
export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_SUCCESS = 'CREATE_POSTSUCCESS';
export const CLEAR_FEED = 'CLEAR_FEED';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';