export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SET_AUTH_ERR_MSG = 'SET_AUTH_ERR_MSG';
export const CLEAR_AUTH_ERR_MSG = 'CLEAR_AUTH_ERR_MSG';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';