exports.INVALID_INPUT = 'INVALID_INPUT';
exports.INCORRECT_CREDENTIALS = 'INCORRECT_CREDENTIALS';
exports.EMAIL_TAKEN = 'EMAIL_TAKEN';
exports.VALIDATION_ERROR = 'VALIDATION_ERROR';
exports.DUPLICATE_FIELDS = 'DUPLICATE_FIELDS';
exports.REQUEST_ERROR = 'REQUEST_ERROR';